### ISSUE TITLE
Doc typo:

### ISSUE THREAD

**Issue by luzengxiangcn** [primihub/primihub-docs#150]
https://github.com/primihub/primihub-docs/blob/main/docs/advance-usage/create-tasks/fedreated-learning/chatglm.md

    "roles":
        {"client":["Alice", "Bob"],
        "server": ["Charlie"]},

typo:
roles：设置每一个参与方的角色行为，例如 Alice 和 Bob 是 server，Charlie 是 client

**Comment by xuefeng-xu** [comment]
@luzengxiangcn 谢谢，文档已修改
