### ISSUE TITLE
redirect website encountes error

### ISSUE THREAD

**Issue by phoenix20162016** [primihub/primihub-docs#178]
https://docs.primihub.com/docs/advance-usage/python-sdk/install/

![image](https://github.com/primihub/primihub-docs/assets/18574396/f0416066-2425-4c96-ac02-d04fdd7287c7)

![image](https://github.com/primihub/primihub-docs/assets/18574396/aea22860-7332-4b34-8fa9-f5ac9a826328)

**Comment by Zjj614** [comment]
#180 
The issue has been fixed. Because of path reference problem
