### ISSUE TITLE
Unable to run node

### ISSUE THREAD

**Issue by Rui-learning** [primihub/primihub-docs#3]
There is no error in the process of compiling the code, but an error is reported when running the node, as shown below:
![image](https://user-images.githubusercontent.com/55970946/174728958-a32b8139-6dfe-46d0-8446-eb1ef7628c02.png)

**Comment by hobo0cn** [comment]
Run 
```
./bazel-bin/node 
```
instead of ./primihub-node under source path.  @Rui-learning
